name: Debug Check

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

env:
  SCCACHE_GHA_ENABLED: "true"
  SCCACHE_CACHE_SIZE: 2G

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.10

      - name: Configure CMake
        run: cmake -B build -S . -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_MSVC_DEBUG_INFORMATION_FORMAT=Embedded -DCMAKE_C_COMPILER_LAUNCHER=sccache -DCMAKE_CXX_COMPILER_LAUNCHER=sccache

      - name: Build project
        run: cmake --build build

      - name: Show sccache stats
        run: sccache --show-stats

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: winhttp-dll-debug
          path: |
            dist/winhttp.dll
            dist/winhttp.pdb
